/*
FOOD_PRODUCT와 FOOD_ORDER 테이블에서 생산일자가 2022년 5월인 식품들의 
식품 ID, 식품 이름, 총매출을 조회하는 SQL문을 작성해주세요. 
이때 결과는 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 
식품 ID를 기준으로 오름차순 정렬해주세요.
*/

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES from FOOD_PRODUCT FP 
join FOOD_ORDER FO ON
FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE EXTRACT( MONTH FROM TO_DATE(FO.PRODUCE_DATE,  'YYYY-MM-DD HH24:MI:SS')) = 5
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;